### ISSUE TITLE
KeyError: 'lora.down.weight'

### ISSUE THREAD

**Issue by wzh125** [tvaranka/fineface#8]
When running demo.py, it occurs.

`Traceback (most recent call last):
  File "/home/wangzihan/fineface/demo.py", line 4, in <module>
    pipe = FineFacePipeline()
           ^^^^^^^^^^^^^^^^^^
  File "/home/wangzihan/fineface/fineface/fineface_pipeline.py", line 46, in __init__
    unet.load_attn_procs(
  File "/home/wangzihan/anaconda3/envs/fineface/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wangzihan/anaconda3/envs/fineface/lib/python3.11/site-packages/diffusers/loaders/unet.py", line 269, in load_attn_procs
    rank = value_dict["lora.down.weight"].shape[0]
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'lora.down.weight'`

**Comment by tvaranka** [comment]
Hi, I ran the demo with a new install using colab and it worked without issues for me.

Just to double check, you installed the requirements.txt and are using correct versions, especially diffusers==0.27.2 and peft==0.7.0.
